CUDA_VISIBLE_DEVICES=0 python ../inference_magic.py\
    --language_model_code_path ../language_model/\
    --language_model_name cambridgeltl/magic_mscoco\
    --clip_path ../clip/\
    --clip_name openai/clip-vit-base-patch32\
    --test_image_prefix_path ../data/mscoco/test_images/\
    --test_path ../data/mscoco/mscoco_test.json\
    --decoding_len 16\
    --k 45\
    --alpha 0.1\
    --beta 2.0\
    --save_path_prefix ../inference_result/mscoco/\
    --save_name magic_result.json